# Task

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Go code generate"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./generated/go/ --go_opt=paths=source_relative --go-grpc_out=./generated/go/ --go-grpc_opt=paths=source_relative
